[versions]
agp = "8.5.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"

gmsGoogleServices = "4.4.2"
firebaseCrashlytics = "3.0.2"
firebaseBomVersion = "33.5.1"

annotations = "1.9.1"
constraintLayout = "2.2.0"
coreKtx = "1.15.0"
splashscreen = "1.2.0-alpha02"
telecom = "1.0.0-alpha03"
media = "1.7.0"
recyclerview = "1.3.2"
slidingpanelayout = "1.2.0"
window = "1.3.0"
gridlayout = "1.0.0"
securityCryptoKtx = "1.1.0-alpha06"
navigation = "2.8.4"
emoji2 = "1.5.0"
car = "1.7.0-beta03"
flexbox = "3.0.0"
#noinspection GradleDependency
protobuf = "3.25.5"
coil = "2.7.0"
dotsIndicator = "5.0"
photoview = "2.3.0"
openidAppauth = "0.11.1"
linphone = "5.4.+"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

androidx-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "annotations" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-telecom = { group = "androidx.core", name = "core-telecom", version.ref = "telecom" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-slidingpanelayout = { group = "androidx.slidingpanelayout", name = "slidingpanelayout", version.ref = "slidingpanelayout" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
androidx-security-crypto-ktx = { group = "androidx.security", name = "security-crypto-ktx", version.ref = "securityCryptoKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-emoji2 = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emoji2" }
androidx-car = { group = "androidx.car.app", name = "app", version.ref = "car" }

google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
google-firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
google-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-protobuf = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-video = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
dots-indicator = { group = "com.tbuonomo", name = "dotsindicator", version.ref = "dotsIndicator" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
openid-appauth = { group = "net.openid", name = "appauth", version.ref = "openidAppauth" }

linphone = { group = "org.linphone", name = "linphone-sdk-android", version.ref = "linphone" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
googleGmsServices = { id = "com.google.gms.google-services", version.ref = "gmsGoogleServices" }


